### ISSUE TITLE
How to get PHPUnit coverage?

### ISSUE THREAD

**Issue by tuanpt-0634** [sun7pro/phpunit-training-coverage#1]
## Coverage driver
Để generate coverage report bằng PHPUnit, cần có [coverage driver](https://github.com/sebastianbergmann/php-code-coverage/tree/master/src/Driver):
![image](https://user-images.githubusercontent.com/49387490/84458779-fe999400-ac8f-11ea-97d2-ffe073c702e1.png)

Có 3 drivers bao gồm (ưu tiên từ trên xuống dưới):
- [pcov](https://github.com/krakjoe/pcov) cho PHPUnit version >= 8
  ```bash
  php -dextension=pcov.so -dpcov.enabled=1 -dpcov.directory=src ./vendor/bin/phpunit --coverage-text
  ```
  > **NOTE**: `pcov.directory=src`, trong đó `src` là thư mục chứa source code
- `phpdbg`
  ```bash
  phpdbg -qrr ./vendor/bin/phpunit --coverage-text
  ```
- XDebug
  ```bash
  XDEBUG_MODE=coverage php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text
  ```

> **NOTE**: chạy trong docker container đã cài sẵn các extension pcov, xdebug

## Coverage format
Có nhiều loại format cho coverage:
```
Code Coverage Options:
  --coverage-clover <file>    Generate code coverage report in Clover XML format
  --coverage-crap4j <file>    Generate code coverage report in Crap4J XML format
  --coverage-html <dir>       Generate code coverage report in HTML format
  --coverage-php <file>       Export PHP_CodeCoverage object to file
  --coverage-text=<file>      Generate code coverage report in text format [default: standard output]
  --coverage-xml <dir>        Generate code coverage report in PHPUnit XML format
```

Nhưng thông dụng nhất là `--coverage-text` thường dùng trong CI hoặc xem nhanh kết quả và `--coverage-html` để xem chi tiết dưới dạng web dashboard và `--coverage-clover` dùng cho Sun*CI

### Tasks
- [ ] Setup project: https://github.com/sun7pro/phpunit-training-coverage
- [ ] Chạy coverage với cả 3 driver và 2 format text, html
- [ ] Comment screenshot cho mỗi lần chạy (coverage text => terminal, coverage html => web page)

**Comment by nganltb-1258** [comment]
# Text Format
## pcov 
![image](https://user-images.githubusercontent.com/49388781/84636519-e1c6c000-af1e-11ea-8659-674f96fbe406.png)
## phpdbg
![image](https://user-images.githubusercontent.com/49388781/84636653-06229c80-af1f-11ea-9737-6ed21fa22cda.png)
## XDebug
![image](https://user-images.githubusercontent.com/49388781/84636748-1cc8f380-af1f-11ea-9abf-d4609aed7a01.png)

# html Format
![image](https://user-images.githubusercontent.com/49388781/84639615-d1184900-af22-11ea-90ce-632077698bd0.png)

**Comment by taipt-0504** [comment]
### PCOV
Coverage Text
![image](https://user-images.githubusercontent.com/49227466/84638697-8944f200-af21-11ea-99e3-6d61a52b47ff.png)
Coverage Html
![image](https://user-images.githubusercontent.com/49227466/84639449-97474280-af22-11ea-8a4f-a4a0e6154bb6.png)
### PHPDBG
Coverage Text
![image](https://user-images.githubusercontent.com/49227466/84638771-9d88ef00-af21-11ea-8309-008d3f26eaf7.png)
Coverage Html
![image](https://user-images.githubusercontent.com/49227466/84639619-d1b0df80-af22-11ea-8a03-1cccb14c924e.png)
### XDEBUG
Coverage Text
![image](https://user-images.githubusercontent.com/49227466/84638877-c315f880-af21-11ea-936a-a3e72c234b99.png)
Coverage Html
![image](https://user-images.githubusercontent.com/49227466/84639759-0886f580-af23-11ea-9206-01a7fa2f190e.png)

**Comment by huongvnq-1722** [comment]
![image](https://user-images.githubusercontent.com/49388972/84639645-daa1b100-af22-11ea-9115-959c1f59a64d.png)
![image](https://user-images.githubusercontent.com/49388972/84640868-754ebf80-af24-11ea-9a8e-8e9d05fd91e4.png)

![image](https://user-images.githubusercontent.com/49388972/84639743-fe64f700-af22-11ea-9513-cc2701454d4e.png)
![image](https://user-images.githubusercontent.com/49388972/84640471-e93c9800-af23-11ea-9850-580acbd62bab.png)
![image](https://user-images.githubusercontent.com/49388972/84639776-0e7cd680-af23-11ea-829e-f5c53440b833.png)

![image](https://user-images.githubusercontent.com/49388972/84640933-8f889d80-af24-11ea-88a1-b0ee86e08692.png)

**Comment by datpn-1648** [comment]
**PCOV**
Coverage Text
![Screenshot from 2020-06-15 17-09-58](https://user-images.githubusercontent.com/48075322/84646210-f067a400-af2b-11ea-8115-5e4692577d8f.png)
Coverage Html
![Screenshot from 2020-06-15 17-15-23](https://user-images.githubusercontent.com/48075322/84646221-f3fb2b00-af2b-11ea-9966-f11478889d68.png)
**PHPDBG**
Coverage Text
![Screenshot from 2020-06-15 17-18-04](https://user-images.githubusercontent.com/48075322/84646375-33c21280-af2c-11ea-9d14-2ad24ed8c4cb.png)
Coverage Html
![Screenshot from 2020-06-15 17-18-56](https://user-images.githubusercontent.com/48075322/84646446-50f6e100-af2c-11ea-95ac-7deeef8068a1.png)
**XDEBUG**
Coverage Text
![Screenshot from 2020-06-15 17-20-21](https://user-images.githubusercontent.com/48075322/84646586-88fe2400-af2c-11ea-86df-16409e166890.png)
Coverage Html
![Screenshot from 2020-06-15 17-21-09](https://user-images.githubusercontent.com/48075322/84646637-a206d500-af2c-11ea-8248-6f2855d8f702.png)
